src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.Register.as_view(), name='register'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout')

]

src/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.CartPageLoader.as_view(), name='cartpageloader'),
    path('confirmation', views.order_confirmation, name='order_confirmation'),
    path('checkout', views.CheckoutLoader.as_view(), name='checkout_page'),
    path('order_history', views.order_history, name='order_history'),
    path('get_cart_items_count', views.get_cart_items_count, name='get_cart_items_count'),
    path('update_', views.update_cart_items, name='update_cart_items'),


]

src/djangobase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from products import views as productviews


router = routers.DefaultRouter()
router.register('categories', productviews.CategoryView)
router.register('suppliers', productviews.SupplierView)
router.register('products', productviews.ProductView)
router.register('productimages', productviews.ProductImageView)

#including the models of a different app here to add them to the api easily
from cart import views as cartviews
router.register('cart', cartviews.CartViewSet)
router.register('cartitem', cartviews.CartItemViewSet)
router.register('checkoutdetails', cartviews.CheckoutDetailsViewSet)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('api/', include(router.urls))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers





app_name = 'products'
urlpatterns = [
    path('', views.BaseLoader.as_view(), name='home'),
    path('category/search/<filter>/', views.BaseLoader.as_view(), name='filter'),
    path('category/search/$', views.product_search, name='product_search'),
    path('api/session/', views.SessionAccess.as_view(), name='xd123'),
    path('api/get_url/', views.get_url, name='get_url_from_django'),
    path('product/<product_id>/', views.product_page, name='product_page'),

]

src/templates/base/base.html
{% load static %}
{% load render_bundle from webpack_loader %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/clss" href="{% static 'base/css/index.css' %}">
    <link rel="icon" href="{% static 'base/imgs/cpu.png' %}"">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    
    <title>
    {% block title %}
        eCommerce Django Vue
    {% endblock %}
    </title>

    {% block base_head %}
    {% endblock %}

    {% block styles %}
    {% endblock %}
</head>
<body>
    <div id="app">

        {% include 'base/header.html' %}
        
        {% block before_container %}
        {% endblock %}

        <div class="container">
            {% block content %}
            {% endblock %}

        </div>
        {% include 'base/footer.html' %}
    </div>
    {% render_bundle 'main' %}

    <!-- loading jquery and bootstrap from an online resource since my server is slow -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

src/templates/base/footer.html
<!-- Footer -->

<br><br><br><br><br><br><br><br><br><br><br>
<footer class="page-footer font-small indigo">

  <!-- Footer Links -->
  <div class="container">

    <!-- Grid row-->
    <hr class="rgba-white-light" style="margin: 0 15%;">

    <!-- Grid row-->
    <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">

      <!-- Grid column -->
      <div class="col-md-8 col-12 mt-5">
        <p style="line-height: 1.72rem"><strong>DISCLAIMER:</strong> please note this site is ment as a demo, its <strong>not a real store</strong>, i dont own any of the products or brands on here and nothing will actaully be shipped, <strong>stripe</strong> (the integrated payment system) is in <strong>test mode</strong>, so <strong>real cards will be declined</strong></p>

        <div class="row">
        <div class="col-6 text-right">
        <br>During checkout use the numbers on the right to advance through the checkout process:
        </div>
        <div class="col-6 text-left">
        <br><br>visa card number: 42 42 42 42 42 42 42 42
        <br>CVC: Any 3 digits 	
        <br>date: Any future date
        </div>
        </div>
        <br>check out the <a href="/api">rest api page</a>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->
    <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">

    <!-- Grid row-->
    <div class="row pb-3">

      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">Made by: Mohammad Rafik <a href="https://github.com/MohammadRafik/ecom_django_vue">github</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

src/templates/base/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand h2" style="margin-right:2rem" href="{% url 'products:home' %}">Electrone</a>

        <div class="navbar-nav mr-auto">
            <form class="form-inline mr-auto" method="get" action="{% url 'products:product_search' %}">
                <input name="search_string" class="form-control mr-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>

        <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'products:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:cartpageloader' %}"><img src="{% static 'base/imgs/shopping-cart.png' %}" width="30px"><span class="badge">[[cart_item_count]]</span></a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{request.user.get_username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'cart:order_history' %}">my orders</a>
                <a class="dropdown-item" href="{% url 'accounts:home' %}">{{request.user.get_username}}'s profile</a>
            </div>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}"><img src="{% static 'base/imgs/user.png' %}" width="30px"></a>
        </li>
        {% endif %}
        {% comment %} <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            #
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'mainapp:home' %}">Action</a>
            <a class="dropdown-item" href="{% url 'mainapp:home' %}">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'mainapp:home' %}">Something else here</a>
            </div>
        </li> {% endcomment %}
        </ul>
    </div>
</nav>

src/templates/base/navigation_old.html
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <h5 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            Navigation
        </h5>
        <ul class="nav flex-column">
            {% comment %} {{categories}} {% endcomment %}
            {% for item in categories %}
                <dropdown :trigger="'hover'" :align="'right'">
                <template slot="btn"><a href="#">{{item}}</a></template>
                <template slot="body">
                    <ul>
                    <li>Custom item</li>
                    <li>
                        <dropdown :trigger="'hover'" :role="'sublist'" :align="'right'">
                        <template slot="btn">Sublist right</template>
                        <template slot="body">
                            Sublist content
                            <ul>
                            <li>Custom subitem</li>
                            <dropdown :trigger="'hover'" :role="'sublist'" :align="'right'">
                                <template slot="btn">Sublist right</template>
                                <template slot="body">Sublist content</template>
                            </dropdown>
                            </ul>
                        </template>
                        </dropdown>
                    </li>
                    </ul>
                </template>
                </dropdown>




                <li class="nav-item">
                    <a class="nav-link">
                        {{item}} created on {{item.created_on}}
                    </a>
                </li>
            {% endfor %}
        </ul>
        <ul class="nav flex-column mb-2">
                            hi xd
        </ul>
    </div>
</nav>