src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.Register.as_view(), name='register'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout')

]

src/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.CartPageLoader.as_view(), name='cartpageloader'),
    path('confirmation', views.order_confirmation, name='order_confirmation'),
    path('checkout', views.CheckoutLoader.as_view(), name='checkout_page'),
    path('order_history', views.order_history, name='order_history'),
    path('get_cart_items_count', views.get_cart_items_count, name='get_cart_items_count'),
    path('update_', views.update_cart_items, name='update_cart_items'),


]

src/djangobase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from products import views as productviews


router = routers.DefaultRouter()
router.register('categories', productviews.CategoryView)
router.register('suppliers', productviews.SupplierView)
router.register('products', productviews.ProductView)
router.register('productimages', productviews.ProductImageView)

#including the models of a different app here to add them to the api easily
from cart import views as cartviews
router.register('cart', cartviews.CartViewSet)
router.register('cartitem', cartviews.CartItemViewSet)
router.register('checkoutdetails', cartviews.CheckoutDetailsViewSet)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('api/', include(router.urls))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers





app_name = 'products'
urlpatterns = [
    path('', views.BaseLoader.as_view(), name='home'),
    path('category/search/<filter>/', views.BaseLoader.as_view(), name='filter'),
    path('category/search/$', views.product_search, name='product_search'),
    path('api/session/', views.SessionAccess.as_view(), name='xd123'),
    path('api/get_url/', views.get_url, name='get_url_from_django'),
    path('product/<product_id>/', views.product_page, name='product_page'),

]

src/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    # username = forms.CharField(length=100)
    email = forms.EmailField(required=True)

    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)
        widgets = {
            'username': forms.TextInput(attrs=({'required': ''})),
            'email': forms.EmailInput(attrs=({'required': ''})),
            'password1':forms.PasswordInput(attrs={'required': ''}),
            'password2':forms.PasswordInput(attrs={'required': ''}),

        }
    
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']

        if commit:
            user.save()
        
        return user

src/accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import RegistrationForm
from django.views import View
from django.contrib.auth import authenticate, login, logout, get_user_model

# Create your views here.
def home(request):
    return render(request, 'accounts/home.html')


class Register(View):
    template_name = 'accounts/register.html'
    form_class = RegistrationForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name,{'form':form})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            # logging the user in since hes registration is successful
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            login(request, user)
            return redirect('../accounts')
        else:
            return render(request, self.template_name, {'form':form})


class Login(View):
    template_name = 'accounts/login.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self,request):
        username = request.POST['username']
        password = request.POST['password']

        User = get_user_model()
        if '@' in username:
            try:
                current_user = User.objects.get(email__iexact=username)
                username = current_user.username
            except:
                error = "Oops! something's wrong. We couldn't find that email"
                return render(request, self.template_name, {'error':error, 'form_username':username})

        user = authenticate(username=username,password=password)

        if user is not None:
            login(request, user)
            return redirect('../accounts')
        else:
            error = "Oops! something's wrong. Your username/email and password didnt match"
            return render(request, self.template_name,  {'error':error, 'form_username':username})


class Logout(View):

    def get(self, request):
        logout(request)
        return redirect('../')

src/accounts/templates/accounts/home.html
{% extends "base/base.html" %}
{% block content %}
    {% if request.user.is_authenticated %}
    <br>
        Hello {{request.user.get_username}}, you are logged in, this is the account home page
        <br><br><br>
        <form onsubmit='' action="{% url 'cart:order_history'%}">
            <div>
                <button type="submit" class="btn btn-info">
                    order history
                </button>
            </div>
        </form>
    <br>
        <form onsubmit="" action="{% url 'accounts:logout' %}" method="get">
        {% csrf_token %}
            <div class="float-left">
                <button type="submit" class="btn btn-warning">
                    Logout
                </button>
            </div>
        </form>
    {% else %}
        You are not logged in
        <br><br>
        <a href="{% url 'accounts:login' %}">Click here</a> to go to the login page
    {% endif %}

{% endblock content %}

src/accounts/templates/accounts/login.html
{% extends 'base/base.html' %}


{% block content %}
{% if request.user.is_authenticated %}
<div class="form-group pt-5">
    <div class="row justify-content-left ml-5">
        <div class="alert alert-success" role="alert">
            <p> Looks like you're already logged in as {{ request.user.username }}</p>
            <p> click <a href="{% url 'accounts:home' %}">here</a> to go back home</p>
        </div>
        <br>
        <div class="container">
            <p> if you would like to log in to a different account you must logout of this one first </p>
            <form onsubmit="" action="{% url 'accounts:logout' %}" method="get">
            {% csrf_token %}
                    <button type="submit" class="btn btn-info">
                        Logout
                    </button>
            </form>
        </div>
    </div>
</div>
{% else %}
<div class="form-group pt-5">
    <div class="row justify-content-left">
        <div class="col-md-8">
            <form onsubmit="" action="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}
                <div class="card">
                <div class="card-header">
                    <h2> User Login </h2>
                </div>
                <div class="card-body">
                    <br>
                    {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endif %}

                    <div class="form-group row">
                        <label for="username" class="col-md-4 col-form-label text-md-right">email or username</label>
                        <div class="col-md-6">
                            <input name='username' type="text" class="form-control" placeholder="username or email" required="" value="{%if form_username %}{{form_username}}{% endif %}"/>
                        </div>
                    </div>


                    <div class="form-group row">
                        <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                        <div class="col-md-6">
                            <input name='password' type="password" class="form-control " placeholder="password" required="" />
                        </div>
                    </div>

                    <div class="col-md-6 offset-md-4">
                        <button type="login" class="btn btn-primary">
                            Sing In
                        </button>
                    </div>
                </div>
                </div>
            </form>
                {% comment %} redirect user to registeration page {% endcomment %}
                <div class="offset-md-7">
                    <p> Dont have an account yet? <a href="{% url 'accounts:register' %}"> Register </a>
                    <br>
                </div>
                <div class="offset-md-8">
                    {% comment %} redirect user to home page {% endcomment %}
                    <p> Take me back <a href="{% url 'products:home' %}"> Home </a> instead </p>
                </div>
        </div>
    </div>
</div>
{% endif %}


{% endblock %}

src/accounts/templates/accounts/register.html
{% extends 'base/base.html' %}


{% block content %}
{% if request.user.is_authenticated %}
<div class="form-group pt-5">
    <div class="row justify-content-left ml-5">
        <div class="alert alert-success" role="alert">
            <p> Looks like you're already logged in as {{ request.user.username }}</p>
            <p> click <a href="{% url 'accounts:home' %}">here</a> to go back to account</p>
        </div>
        <br>
        <div class="container">
            <p> if you would like to register a new account you must logout of this one first </p>
            <form onsubmit="" action="{% url 'accounts:logout' %}" method="get">
            {% csrf_token %}
                    <button type="submit" class="btn btn-info">
                        Logout
                    </button>
            </form>
        </div>
    </div>
</div>
{% else %}

<div class="form-group pt-5">
    <div class="row justify-content-left">
        <div class="col-md-8">
            <form onsubmit="" action="{% url 'accounts:register' %}" method="post">
                {% csrf_token %}
                <div class="card">
                <div class="card-header">
                    <h2> Registration </h2>
                </div>
                <div class="card-body">
                    <br>
                    <div class="form-group row">
                        <label for="full_name" class="col-md-4 col-form-label text-md-right">Full Name</label>
                        <div class="col-md-6">
                            <input name="{{ form.username.name }}" type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" placeholder="username" required="" value="{{ form.username.value|default:'' }}" />
                            {% if form.username.errors %}
                            <div class="invalid-feedback">
                                {{ form.username.errors|first|safe }}
                            </div>
                            {% endif %}
                        </div>


                    </div>

                    <div class="form-group row">
                        <label for="email_address" class="col-md-4 col-form-label text-md-right">E-Mail Address</label>
                        <div class="col-md-6">
                            <input name="{{ form.email.name }}" type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" placeholder="Email" required="" value="{{ form.email.value|default:'' }}" />
                            {% if form.email.errors %}
                            <div class="invalid-feedback">
                                {{ form.email.errors|first|safe }}
                            </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                        <div class="col-md-6">
                            <input name="{{ form.password1.name }}" type="password" class="form-control {% if form.password1.errors %}is-invalid{% endif %}" placeholder="password" required="" value="{{ form.password1.value|default:'' }}" />
                            {% if form.password1.errors %}
                            <div class="invalid-feedback">
                                {{ form.password1.errors|first|safe }}
                            </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="repeat-password" class="col-md-4 col-form-label text-md-right">Repeat-Password</label>
                        <div class="col-md-6">
                            <input name="{{ form.password2.name }}" type="password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}" placeholder="repeat password" required="" value="{{ form.password2.value|default:'' }}" />
                            {% if form.password2.errors %}
                            <div class="invalid-feedback">
                                {{ form.password2.errors|first|safe }}
                            </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Register
                        </button>
                    </div>
                </div>
                </div>
            </form>
            <br>
                {% comment %} redirect user to registeration page {% endcomment %}
                <div class="offset-md-7">
                    <p> Already have an account? <a href="{% url 'accounts:login' %}"> Login </a>
                    <br>
                </div>
                <div class="offset-md-7">
                    {% comment %} redirect user to home page {% endcomment %}
                    <p> Take me back <a href="{% url 'products:home' %}"> Home </a> instead </p>
                </div>
        </div>
    </div>
</div>

{%endif%}

{% endblock %}