src/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.CartPageLoader.as_view(), name='cartpageloader'),
    path('confirmation', views.order_confirmation, name='order_confirmation'),
    path('checkout', views.CheckoutLoader.as_view(), name='checkout_page'),
    path('order_history', views.order_history, name='order_history'),
    path('get_cart_items_count', views.get_cart_items_count, name='get_cart_items_count'),
    path('update_', views.update_cart_items, name='update_cart_items'),


]

src/djangobase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from products import views as productviews


router = routers.DefaultRouter()
router.register('categories', productviews.CategoryView)
router.register('suppliers', productviews.SupplierView)
router.register('products', productviews.ProductView)
router.register('productimages', productviews.ProductImageView)

#including the models of a different app here to add them to the api easily
from cart import views as cartviews
router.register('cart', cartviews.CartViewSet)
router.register('cartitem', cartviews.CartItemViewSet)
router.register('checkoutdetails', cartviews.CheckoutDetailsViewSet)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('api/', include(router.urls))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers





app_name = 'products'
urlpatterns = [
    path('', views.BaseLoader.as_view(), name='home'),
    path('category/search/<filter>/', views.BaseLoader.as_view(), name='filter'),
    path('category/search/$', views.product_search, name='product_search'),
    path('api/session/', views.SessionAccess.as_view(), name='xd123'),
    path('api/get_url/', views.get_url, name='get_url_from_django'),
    path('product/<product_id>/', views.product_page, name='product_page'),

]

src/cart/models.py
from django.db import models
from products.models import Product
from django.contrib.auth.models import User, AnonymousUser


# Create your models here.
#add functionality to be able to change its quantity

class Cart(models.Model):
    user = models.ForeignKey(User,null=True,blank=True, default=None, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    updated_by = models.CharField(max_length=100)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)



    def get_items(self):
        return self.cart_items.prefetch_related('product').all()

    @classmethod
    def delete_unactive_carts(cls):
    # deletes all non-active cart instances
        cls.objects.filter(active=False).delete()

    @classmethod
    def delete_all_carts(cls):
        cls.objects.all().delete()



class CartItem(models.Model):
    
    cart = models.ForeignKey(Cart, related_name='cart_items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    updated_by = models.CharField(max_length=100)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)

    def __str__(self):
        return self.product.title + ' cart item from cart object ' + str(self.cart.id)

    def find_total_cost(self):
        tax = 1.12
        self.total_cost = self.quantity * self.product.current_price * tax
        return self.total_cost

    def update_quantity(self, quantity):
        self.update(quantity=quantity)



class CheckoutDetails(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    cart = models.OneToOneField(Cart, related_name='checkout_details', null=True, on_delete=models.SET_NULL)
    name_of_receiver = models.CharField(max_length=100)
    main_address = models.CharField(max_length=200)
    secondary_address = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100)
    province = models.CharField(max_length=20)
    postal_code = models.CharField(max_length=12)
    phone_number = models.CharField(max_length=12)
    updated_by = models.CharField(max_length=100)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)

    def __str__(self):
        return  'products to ' + self.main_address + ' for ' + self.name_of_receiver
    

src/cart/forms.py
from django import forms
from cart.models import CheckoutDetails

class CheckoutForm(forms.ModelForm):

    class Meta:
        model = CheckoutDetails
        fields = [ 'name_of_receiver', 'main_address', 'secondary_address', 'city', 'province', 'postal_code', 'phone_number']
        widgets = {
            'name_of_receiver': forms.TextInput(attrs={'class': 'form-control'}),
            'main_address': forms.TextInput(attrs={'class': 'form-control'}),
            'secondary_address': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'province': forms.TextInput(attrs={'class': 'form-control'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'})
        }


    def __init__(self, *args, **kwargs):
        super(CheckoutForm, self).__init__(*args, **kwargs)

        # here we just change the secondary address field so that it wont be required by the frontend
        self.fields['secondary_address'].required = False

src/cart/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views import View
from cart.models import Cart,CartItem, CheckoutDetails
from products.models import ProductImage, Product
from django.conf import settings
from django.contrib.auth.models import User, AnonymousUser
from cart.utils.cart_management import CartManager
import re
# Create your views here.



class CartPageLoader(View):
    def get(self, request):

        cart_manager = CartManager(request)
        cart_manager.load_items()
        cart_manager.total_cost()
        total_cost_for_stripe = cart_manager.total_cost_with_tax * 100

        # load product images
        product_images = []
        if hasattr(cart_manager, 'cart_items'):

            cart_product_ids = set()
            for cart_item in cart_manager.cart_items:
                cart_product_ids.add(cart_item.product.id)

            for cart_product_id in cart_product_ids:
                product_images.append(ProductImage.find_main_product_image(cart_product_id))


        # get stipe key
        stripe_key = settings.STRIPE_PUBLISHABLE_KEY


        return render(request, 'cart/home.html', {'cart':cart_manager.cart, 'cart_items':cart_manager.cart_items, 'product_images':product_images, 'total_cost':cart_manager.total_cost,'tax':cart_manager.tax, 'total_cost_with_tax':cart_manager.total_cost_with_tax, 'stripe_key':stripe_key, 'total_cost_for_stripe':total_cost_for_stripe})


from cart.forms import CheckoutForm
class CheckoutLoader(View):
    checkout_template_name = 'cart/checkout_page.html'


    def get(self, request):
        form = CheckoutForm()
        return render(request, self.checkout_template_name, {'form':form})

    def post(self, request):
        form = CheckoutForm(request.POST)
        if form.is_valid():
            cart_manager = CartManager(request)
            cart_manager.load_items()
            cart_manager.total_cost()
            total_cost_for_stripe = cart_manager.total_cost_with_tax * 100
            
            stripe_key = settings.STRIPE_PUBLISHABLE_KEY

            if request.user.is_authenticated:
                user_name = request.user.get_username()
            else:
                user_name = ''

            # check if checkoutDetails object already exists, if yes update it, if no make one
            if CheckoutDetails.objects.filter(cart_id = cart_manager.cart.id).count():
                checkout_details = CheckoutDetails.objects.get(cart_id = cart_manager.cart.id)
                if request.user.is_authenticated:
                    checkout_details.user = request.user
                checkout_details.cart = cart_manager.cart
                checkout_details.name_of_receiver = form.cleaned_data['name_of_receiver']
                checkout_details.main_address = form.cleaned_data['main_address']
                checkout_details.secondary_address = form.cleaned_data['secondary_address']
                checkout_details.city = form.cleaned_data['city']
                checkout_details.province = form.cleaned_data['province']
                checkout_details.postal_code = form.cleaned_data['postal_code']
                checkout_details.phone_number = form.cleaned_data['phone_number']
                checkout_details.updated_by = user_name
                checkout_details.created_by = user_name
                checkout_details.save()
            else:
                if request.user.is_authenticated:
                    checkout_details = CheckoutDetails( user = request.user, cart = cart_manager.cart, name_of_receiver = form.cleaned_data['name_of_receiver'], main_address = form.cleaned_data['main_address'], secondary_address = form.cleaned_data['secondary_address'], city = form.cleaned_data['city'], province = form.cleaned_data['province'], postal_code = form.cleaned_data['postal_code'], phone_number = form.cleaned_data['phone_number'], updated_by = user_name, created_by = user_name)
                else:
                    checkout_details = CheckoutDetails(cart = cart_manager.cart, name_of_receiver = form.cleaned_data['name_of_receiver'], main_address = form.cleaned_data['main_address'], secondary_address = form.cleaned_data['secondary_address'], city = form.cleaned_data['city'], province = form.cleaned_data['province'], postal_code = form.cleaned_data['postal_code'], phone_number = form.cleaned_data['phone_number'], updated_by = user_name, created_by = user_name)
            checkout_details.save()


            return render(request, 'cart/make_payment.html', { 'form': form,'checkout_details':checkout_details, 'cart':cart_manager.cart, 'cart_items':cart_manager.cart_items, 'total_cost':cart_manager.total_cost,'tax':cart_manager.tax, 'total_cost_with_tax':cart_manager.total_cost_with_tax, 'stripe_key':stripe_key, 'total_cost_for_stripe':total_cost_for_stripe})
        else:
            return render(request, self.checkout_template_name, {'form':form})
            

def update_cart_items(request):
    if request.method == 'GET':
        return HttpResponse('no access')
    elif request.method == 'POST':
        cart_manager = CartManager(request)
        import ast
        dict_request_body = ast.literal_eval(request.body.decode("UTF-8"))
        product_url = dict_request_body['product']
        try:
            product_id_with_slashes = re.search(r'\/[0-9]{1,6}\/', product_url).group()
            product_id = re.search(r'[0-9]{1,6}', product_id_with_slashes).group()
            product_id = int(product_id)
            product = Product.objects.get(pk = product_id)
            try:
                cart_item_being_updated = CartItem.objects.get(product = product, cart = cart_manager.cart)
                cart_item_being_updated.quantity += 1
                cart_item_being_updated.save()
            except:
                # if we get here means cart item doesnt exist so we make a new one with quanitity of 1
                new_cart_item = CartItem(cart = cart_manager.cart, product = product)
                new_cart_item.save()
        except:
            HttpResponse('someone is messing with the hidden html input fields D:')
            
        return HttpResponse('updated cart items')
        





            
def order_confirmation(request):
    cart_manager = CartManager(request)
    cart_manager.load_items()
    cart_manager.total_cost()
    total_cost_for_stripe = cart_manager.total_cost_with_tax * 100


    # load main image for each cart item product, should maybe redo this main img finder
    product_images =  []
    repeated = False
    if hasattr(cart_manager, 'cart_items'):
        for cart_item in cart_manager.cart_items:
            img_in_list = ProductImage.find_main_product_image(cart_item.product.id)
            repeated = False
            for product_image in product_images:
                if product_image.pk == img_in_list.pk:
                    repeated = True
                    break
            if not repeated:
                product_images.append(img_in_list)
                repeated = False

    if request.method == "GET":
        payment_confirmation = ''
    elif request.POST['payment_confirmation']:
        payment_confirmation = float(request.POST['payment_confirmation'])
    else:
        payment_confirmation = ''


    # deactivate this cart now
    cart_manager.deactivate(request)
    # cant delete deactiveated carts because they are needed to load order history

    return render(request, 'cart/order_confirmation.html', {'cart':cart_manager.cart, 'cart_items':cart_manager.cart_items, 'product_images':product_images, 'total_cost':cart_manager.total_cost,'tax':cart_manager.tax, 'total_cost_with_tax':cart_manager.total_cost_with_tax, 'total_cost_for_stripe':total_cost_for_stripe, 'payment_confirmation':payment_confirmation, 'true_string':'True'})



def order_history(request):
    order_history = CheckoutDetails.objects.filter(user_id = request.user.id)
    cart_items_list = []
    product_images = []
    total_costs = []
    for order in order_history:
        cart_items = order.cart.get_items()
        cart_items_list.append(cart_items)
        #get product images
        repeated = False
        if cart_items:
            for cart_item in cart_items:
                img_in_list = ProductImage.find_main_product_image(cart_item.product.id)
                repeated = False
                for product_image in product_images:
                    if product_image.pk == img_in_list.pk:
                        repeated = True
                        break
                if not repeated:
                    product_images.append(img_in_list)
                    repeated = False
        #get order total cost
        total_cost = 0.0
        for cart_item in cart_items:
            total_cost += (float(cart_item.product.current_price) * cart_item.quantity)
        total_cost = round(total_cost, 2)
        total_cost_with_tax = total_cost*1.13
        total_cost_with_tax = round(total_cost_with_tax, 2)
        total_costs.append(total_cost_with_tax)

    order_cartitem_history = zip( order_history, cart_items_list, total_costs)
    return render(request, 'cart/order_history.html', {'orders':order_history, 'order_cartitem_history':order_cartitem_history, 'product_images':product_images})

    
    
def get_cart_items_count(request):
    cart_manager = CartManager(request)
    return HttpResponse(cart_manager.calc_quanitity())


# ---------------------------------------------#
#-----------------rest framework---------------#
# ---------------------------------------------#
from rest_framework import viewsets
from .serializers import CartItemSerializer, CartSerializer, CheckoutDetailsSerializer

class CartItemViewSet(viewsets.ModelViewSet):
    queryset = CartItem.objects.all()
    serializer_class = CartItemSerializer

class CartViewSet(viewsets.ModelViewSet):
    queryset = Cart.objects.all()
    serializer_class = CartSerializer

class CheckoutDetailsViewSet(viewsets.ModelViewSet):

src/cart/templates/cart/checkout_page.html
{% extends "base/base.html" %}
{% block content %}

<br>
please fill out this form so we can get your shipping address and other needed data, then proceed to the payment page
<br><br>
{% if request.user.is_authenticated == False %}
    <div class="alert alert-danger" role="alert">
    please note that if you are not logged in you will not be able to look at your order history later on
    </div>
{%endif%}

<br>
<form action="{% url 'cart:checkout_page' %}" method='post'>
    {% csrf_token %}
    <div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-10">
        {% for field in form %}
            <div class="form-group row">
            <label class="col-sm-3">{{field.label_tag}}</label>
            <div class="col-sm-6">
            {{field}}
            </div>
            </div>
        {% endfor %}
    <input type='submit' class="float-right" value='Review order and pay'>
    </div>
    </div>

</form>



{% endblock content %}

src/cart/templates/cart/home.html
{% extends "base/base.html" %}
{% block content %}
<br>
<div class="row">
    <div class="col-sm-9">
        <div class="card">
            <div class="card-header">
                Cart Porudcts
            </div>
            <ul class="list-group list-group-flush">
                {% for cart_item in cart_items%}
                    <li class="list-group-item">
                    <strong>{{cart_item.product.title}}</strong>
                    {% for product_image in product_images %}
                        {% if product_image.product_id == cart_item.product_id %}
                            <br><img src="/media/{{product_image.image_url}}" width='50'>
                            <p class="text-right"><strong>CDN${{cart_item.product.current_price}}</strong> x {{cart_item.quantity}}</p>
                        {% endif %}
                    {% endfor %}
                {% comment %} button to remove item from cart {% endcomment %}
                    <form v-on:submit.prevent="delete_item_from_cart({{cart_item.id}})" method="delete">
                        {% csrf_token %}    
                        <button class="btn-warning" type="submit">remove from cart</button>
                    </form>
                    
                    </li>
                {% empty %}
                    <li class="list-group-item">
                        you dont have any products in your cart
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    {% comment %} total cost {% endcomment %}
    <div class="col-sm-3">
        <div class="float-right">
            <ul class="list-group">
                <li class="list-group-item">
                    total before tax: {{total_cost}}
                    <br>
                    Tax: {{tax}}
                </li>
                <li class="list-group-item">
                final price:<br><br>
                    <div class="float-right">
                        CDN${{total_cost_with_tax}}


                        {% if cart_items%}
                            <form action="{% url 'cart:checkout_page' %}" method="get">
                                <button class="btn-info"> proceed to checkout </button>
                            </form>
                        {% endif %}







                    </div>
                    {% comment %} checkout {% endcomment %}
                    <br>
                </li>
            </ul>
        </div>
        <br><br><br><br><br><br><br>
    </div>
</div>







<br><br><br><br><br><br><br>
<br><br><br><br><br><br><br>
{% endblock content %}

src/cart/templates/cart/make_payment.html
{% extends "base/base.html" %}
{% block content %}
<br>
<h4 > final step, please make sure all the data is correct, then proceed to make payment:</h4>
<p> shipping address: &#160;{{checkout_details.main_address}}, {{ checkout_details.city }}, {{checkout_details.province}}</p>
<p> postal code: &#160;{{checkout_details.postal_code}}</p>
<p> name of receiver: &#160;{{checkout_details.name_of_receiver}}</p>
<br>
<h4> purchasing the following items:<h4>
<br>
<div class="card">
    <div class="card-header">
        Porudcts you are purchasing
    </div>
    <ul class="list-group list-group-flush">
        {% for cart_item in cart_items%}
            <li class="list-group-item">
            <strong>{{cart_item.product.title}}</strong>
            <p class="text-right"><strong>CDN${{cart_item.product.current_price}}</strong> x {{cart_item.quantity}}</p>
            </li>
        {% empty %}
            <li class="list-group-item">
                you dont have any products in your cart
            </li>
        {% endfor %}
    </ul>
</div>

{% comment %} total cost {% endcomment %}
<br><br><br>
<div class="col-sm-3">
<div class="float-right">
    <ul class="list-group">
        <li class="list-group-item">
            total before tax: {{total_cost}}
            <br>
            Tax: {{tax}}
        </li>
        <li class="list-group-item">
        final price:<br><br>
            <div class="float-right">
                CDN${{total_cost_with_tax}}
                <form action="{% url 'cart:order_confirmation' %}" method="post">
                {% csrf_token %}
                <checkout_script stripe_key="{{stripe_key}}" total_cost="{{total_cost_for_stripe}}"></checkout_script>
                <input type="hidden" name="payment_confirmation" value="{{total_cost_with_tax}}">
                </form>
            </div>
            {% comment %} checkout {% endcomment %}
            <br>
        </li>
    </ul>
</div>
</div>
<br><br><br><br><br><br><br>
<br><br><br><br><br><br><br>
<br><br><br><br>


<br><br><br>

{% endblock content %}

src/cart/templates/cart/order_confirmation.html
{% extends "base/base.html" %}
{% block content %}
<br>
{% comment %} this is a simple check, its not important if it fails, its just a check to see what part of the html should be loaded {% endcomment %}
{% if payment_confirmation == total_cost_with_tax %}
    <ul class="list-group">
    <h4 ><div class="alert alert-success" role="alert"> Your order has been successfully processed</div> the total cost was CDN$ {{ total_cost_with_tax}} for the following products:</h4>
        {% for cart_item in cart_items %}
            <li class="list-group-item">
                <strong>
                    {{cart_item.product.title}}
                </strong>
            </li>
        {% empty %}
        wait hold on, you didnt even buy anything! how did you reach this page!!! >:( im reporting you to the internet police!!

        {% endfor %}
    </ul>

    <br><br><br>
    <div class="float">
        <h4> Thank You!</h4>
        {% comment %} redirect user to home page {% endcomment %}
        <p> Take me back <a href="{% url 'products:home' %}"> Home </a> </p>
    </div>
{% else %}
<div class="float">
    <p></p>
    <h4> Error, your order confirmation failed. did you pay?</h4>
    {% comment %} redirect user to home page {% endcomment %}
    <p> Take me back <a href="{% url 'products:home' %}"> Home </a> </p>
</div>
{% endif %}
{% endblock content %}

src/cart/templates/cart/order_history.html
{% extends "base/base.html" %}
{% block content %}
<br>
<p>this is a list of all you're previouse orders:<p>
{% for order, cart_items, cost in order_cartitem_history %}



<div class="row">
    <div class="col-sm-9">
        <div class="card">
            <div class="card-header">
                Order #{{order.id}}
                <div class="float-right">
                    total cost: CDN${{cost}}
                </div>
            </div>
            <ul class="list-group list-group-flush">
                {% comment %} list of cart items for 1 order {% endcomment %}
                {% for cart_item in cart_items %}
                    <li class="list-group-item">
                    <strong>{{cart_item.product.title}}</strong>
                    {% for product_image in product_images %}
                        {% if product_image.product_id == cart_item.product_id %}
                            <br><img src="/media/{{product_image.image_url}}" width='50'>
                            <p class="text-right"><strong>CDN${{cart_item.product.current_price}}</strong> x {{cart_item.quantity}}</p>
                        {% endif %}
                    {% endfor %}
                    </li>
                {% endfor %}
            </ul>
            <div class="card-footer">
                <p>
                    address shipped to: {{order.main_address}}, {{order.city}}, {{order.province}}
                </p>
                <p>
                    person shipped to: {{order.name_of_receiver}}
                </p>
                <div class="float-right">
                    Order placed on: {{order.created_on}}
                </div>
            </div>
        </div>
    </div>
</div>
<br><br>
{% empty %}
it looks like you have not ordered anything, or maybe you made your orders without being logged in
{% endfor %}
{% endblock content %}